from io_common import safe_print


def print_overview():
    safe_print('🔎 Google Search Skill · 功能总览 / 速查')
    safe_print('=' * 44)
    safe_print('')
    safe_print('基础搜索:')
    safe_print('  web/search      普通 Google 搜索')
    safe_print('  images          图片搜索')
    safe_print('  videos          视频搜索')
    safe_print('  news            新闻搜索')
    safe_print('  shopping        购物搜索')
    safe_print('  scholar         学术搜索')
    safe_print('  patents         专利搜索')
    safe_print('')
    safe_print('本地/地图:')
    safe_print('  places          地点搜索')
    safe_print('  maps            地图/本地结果，带 placeId/cid/fid')
    safe_print('  reviews         评论查询（必须带 --place-id / --cid / --fid）')
    safe_print('  maps-reviews    先 maps 再 reviews，可配 --pick N / 有界 --all')
    safe_print('')
    safe_print('提取/识别:')
    safe_print('  autocomplete    搜索建议/自动补全')
    safe_print('  webpage         网页正文提取（参数是 URL）')
    safe_print('  lens            以图片 URL 做 Lens 查询（参数是 URL）')
    safe_print('')
    safe_print('常用开关:')
    safe_print('  --json          包装后的 JSON 输出')
    safe_print('  --raw           原始 API JSON 输出')
    safe_print('  --compact       单行 JSON，方便管道')
    safe_print('  --save <file>   保存 JSON 到文件')
    safe_print('  --pick <N>      maps-reviews 选第 N 个地点')
    safe_print('  --all           maps-reviews 处理前 --num 个地点（1-10）')
    safe_print('  --limit <N>     限制 pretty 输出条数')
    safe_print('')
    safe_print('常用例子:')
    safe_print('  # 以下命令均从 skill 根目录运行')
    safe_print('  /bin/bash -p scripts/run.sh web "OpenAI"')
    safe_print('  /bin/bash -p scripts/run.sh maps "coffee shanghai"')
    safe_print('  /bin/bash -p scripts/run.sh maps-reviews "coffee shanghai" --pick 2')
    safe_print('  /bin/bash -p scripts/run.sh reviews --place-id ChIJ...')
    safe_print('  /bin/bash -p scripts/run.sh lens "https://example.com/image.jpg" --json')
    safe_print('')
    safe_print('更多示例见 references/examples.md 或运行:')
    safe_print('  /bin/bash -p scripts/run.sh examples')
    safe_print('')
    safe_print('健康检查:')
    safe_print('  /bin/bash -p scripts/check.sh                 # 完全离线')
    safe_print('  /bin/bash -p scripts/check.sh --online-smoke')
    safe_print('  /bin/bash -p scripts/check.sh --online-full')
    safe_print('  自动化参考: references/automation.md')
    safe_print('')
    safe_print('别名: overview / cheatsheet / quickref / help')


def print_examples():
    safe_print('📚 Google Search Skill · 示例命令')
    safe_print('=' * 36)
    safe_print('')
    safe_print('# 普通搜索')
    safe_print('# 以下命令均从 skill 根目录运行')
    safe_print('/bin/bash -p scripts/run.sh web "OpenAI"')
    safe_print('/bin/bash -p scripts/run.sh "OpenAI" 3 1 us en  # legacy: query num page gl hl')
    safe_print('')
    safe_print('# 地图 / 评论')
    safe_print('/bin/bash -p scripts/run.sh maps "coffee shanghai"')
    safe_print('/bin/bash -p scripts/run.sh reviews --place-id ChIJ...')
    safe_print('/bin/bash -p scripts/run.sh reviews --cid 1234567890')
    safe_print('/bin/bash -p scripts/run.sh reviews --fid 0x123456:0xabcdef')
    safe_print('/bin/bash -p scripts/run.sh maps-reviews "coffee shanghai" --pick 2 --limit 3')
    safe_print('/bin/bash -p scripts/run.sh maps-reviews "coffee shanghai" --all --num 10')
    safe_print('')
    safe_print('# 网页 / Lens')
    safe_print('/bin/bash -p scripts/run.sh webpage "https://openclaw.ai"')
    safe_print('/bin/bash -p scripts/run.sh lens "https://example.com/image.jpg" --json --compact')
    safe_print('')
    safe_print('# 更多完整示例请看 references/examples.md')
