#!/usr/bin/env python3
from io_common import safe_print


def print_overview():
    safe_print('🔎 Google Search Skill · 功能总览 / 速查')
    safe_print('=' * 44)
    safe_print('')
    safe_print('基础搜索:')
    safe_print('  web/search      普通 Google 搜索')
    safe_print('  images          图片搜索')
    safe_print('  videos          视频搜索')
    safe_print('  news            新闻搜索')
    safe_print('  shopping        购物搜索')
    safe_print('  scholar         学术搜索')
    safe_print('  patents         专利搜索')
    safe_print('')
    safe_print('本地/地图:')
    safe_print('  places          地点搜索')
    safe_print('  maps            地图/本地结果，带 placeId/cid/fid')
    safe_print('  reviews         评论查询（必须带 --place-id / --cid / --fid）')
    safe_print('  maps-reviews    先 maps 再 reviews，可配 --pick N / --all')
    safe_print('')
    safe_print('提取/识别:')
    safe_print('  autocomplete    搜索建议/自动补全')
    safe_print('  webpage         网页正文提取（参数是 URL）')
    safe_print('  lens            以图片 URL 做 Lens 查询（参数是 URL）')
    safe_print('')
    safe_print('常用开关:')
    safe_print('  --json          包装后的 JSON 输出')
    safe_print('  --raw           原始 API JSON 输出')
    safe_print('  --compact       单行 JSON，方便管道')
    safe_print('  --save <file>   保存 JSON 到文件')
    safe_print('  --pick <N>      maps-reviews 选第 N 个地点')
    safe_print('  --all           maps-reviews 对全部地点抓评论')
    safe_print('  --limit <N>     限制 pretty 输出条数')
    safe_print('')
    safe_print('常用例子:')
    safe_print('  search.py web "OpenAI"')
    safe_print('  search.py maps "coffee shanghai"')
    safe_print('  search.py maps-reviews "coffee shanghai" --pick 2')
    safe_print('  search.py maps-reviews "coffee shanghai" --all --limit 3')
    safe_print('  search.py reviews --place-id ChIJ...')
    safe_print('  search.py webpage "https://openclaw.ai"')
    safe_print('  search.py lens "https://example.com/image.jpg" --json')
    safe_print('')
    safe_print('更多示例:')
    safe_print('  search.py examples')
    safe_print('')
    safe_print('自检:')
    safe_print('  python3 scripts/selfcheck.py')
    safe_print('  python3 scripts/selfcheck.py --full')
    safe_print('')
    safe_print('别名: overview / cheatsheet / quickref / help')


def print_examples():
    safe_print('📚 Google Search Skill · 示例命令')
    safe_print('=' * 36)
    safe_print('')
    safe_print('# 普通搜索')
    safe_print('search.py web "OpenAI"')
    safe_print('search.py "OpenAI" 3 1 us en  # legacy positional 示例：query num page gl hl')
    safe_print('')
    safe_print('# 新闻 / 图片 / 专利')
    safe_print('search.py news "OpenAI" --limit 5')
    safe_print('search.py images "cute cat" --json')
    safe_print('search.py patents "OpenAI" --raw')
    safe_print('')
    safe_print('# 地图 / 评论')
    safe_print('search.py maps "coffee shanghai"')
    safe_print('search.py maps-reviews "coffee shanghai" --pick 2 --limit 3')
    safe_print('search.py maps-reviews "coffee shanghai" --all --limit 2')
    safe_print('search.py reviews --place-id ChIJ...')
    safe_print('')
    safe_print('# 网页 / Lens')
    safe_print('search.py webpage "https://openclaw.ai"')
    safe_print('search.py lens "https://example.com/image.jpg" --json --compact')
    safe_print('')
    safe_print('# 机器可读输出')
    safe_print('search.py web "OpenAI" --json --save /tmp/serper.json')
    safe_print('search.py maps-reviews "coffee shanghai" --all --raw --compact')
